// Generated by CoffeeScript 1.3.3
(function() {

  this.Study = this.Study || {
    foo: function() {
      return "bar";
    },
    hoge: function() {
      return Study.fuga;
    },
    fuga: {}
  };

}).call(this);
