// Generated by CoffeeScript 1.3.3
(function() {
  var config;

  config = module.exports;

  config["config template"] = {
    rootPath: "../",
    libs: [],
    sources: ["src/**/*.js"],
    tests: ["test/**/*_test.js", "spec/**/*_spec.js"],
    resources: []
  };

}).call(this);
